const ACTION_TYPES = {
  //======================== LOGIN =======================//
  LOGIN_API_PENDING: 'LOGIN_API_PENDING',
  LOGIN_API_SUCCESS: 'LOGIN_API_SUCCESS',
  LOGIN_API_ERROR: 'LOGIN_API_ERROR',

  //======================== REGISTER ========================//
  REGISTER_API_PENDING: 'REGISTER_API_PENDING',
  REGISTER_API_SUCCESS: 'REGISTER_API_SUCCESS',
  REGISTER_API_ERROR: 'REGISTER_API_ERROR',

  //======================== WISHLISTS ========================//
  WISHLISTS_API_PENDING: 'WISHLISTS_API_PENDING',
  WISHLISTS_API_SUCCESS: 'WISHLISTS_API_SUCCESS',
  WISHLISTS_API_ERROR: 'WISHLISTS_API_ERROR',

  WISHLISTS_ADD_API_PENDING: 'WISHLISTS_ADD_API_PENDING',
  WISHLISTS_ADD_API_SUCCESS: 'WISHLISTS_ADD_API_SUCCESS',
  WISHLISTS_ADD_API_ERROR: 'WISHLISTS_ADD_API_ERROR',

  //======================== MASTERS ========================//
  REFUGEES_API_PENDING: 'REFUGEES_API_PENDING',
  REFUGEES_API_SUCCESS: 'REFUGEES_API_SUCCESS',
  REFUGEES_API_ERROR: 'REFUGEES_API_ERROR',

  DONOR_API_PENDING: 'DONOR_API_PENDING',
  DONOR_API_SUCCESS: 'DONOR_API_SUCCESS',
  DONOR_API_ERROR: 'DONOR_API_ERROR',

  SHELTERS_API_PENDING: 'SHELTERS_API_PENDING',
  SHELTERS_API_SUCCESS: 'SHELTERS_API_SUCCESS',
  SHELTERS_API_ERROR: 'SHELTERS_API_ERROR',

  REQUESTS_API_PENDING: 'REQUESTS_API_PENDING',
  REQUESTS_API_SUCCESS: 'REQUESTS_API_SUCCESS',
  REQUESTS_API_ERROR: 'REQUESTS_API_ERROR',

  MEETING_STATUS_API_PENDING: 'MEETING_STATUS_API_PENDING',
  MEETING_STATUS_API_SUCCESS: 'MEETING_STATUS_API_SUCCESS',
  MEETING_STATUS_API_ERROR: 'MEETING_STATUS_API_ERROR',

  //======================== PROFILE ========================//
  PROFILE_API_PENDING: 'PROFILE_API_PENDING',
  PROFILE_API_SUCCESS: 'PROFILE_API_SUCCESS',
  PROFILE_API_ERROR: 'PROFILE_API_ERROR',

  //======================== CONTACT-US ========================//
  CONTACT_US_API_PENDING: 'CONTACT_US_API_PENDING',
  CONTACT_US_API_SUCCESS: 'CONTACT_US_API_SUCCESS',
  CONTACT_US_API_ERROR: 'CONTACT_US_API_ERROR',

  //======================== HELPED ========================//
  HELPED_API_PENDING: 'HELPED_API_PENDING',
  HELPED_API_SUCCESS: 'HELPED_API_SUCCESS',
  HELPED_API_ERROR: 'HELPED_API_ERROR',

  //======================== PEOPLE ========================//
  PEOPLE_API_PENDING: 'PEOPLE_API_PENDING',
  PEOPLE_API_SUCCESS: 'PEOPLE_API_SUCCESS',
  PEOPLE_API_ERROR: 'PEOPLE_API_ERROR',

  //======================== CREATE-MEETING ========================//
  CREATE_MEETING_API_PENDING: 'CREATE_MEETING_API_PENDING',
  CREATE_MEETING_API_SUCCESS: 'CREATE_MEETING_API_SUCCESS',
  CREATE_MEETING_API_ERROR: 'CREATE_MEETING_API_ERROR',

  //======================== MEETING ========================//
  MEETING_API_PENDING: 'MEETING_API_PENDING',
  MEETING_API_SUCCESS: 'MEETING_API_SUCCESS',
  MEETING_API_ERROR: 'MEETING_API_ERROR',

};
export default ACTION_TYPES;